### ISSUE TITLE
Can we get rid of `unsafe_eval`?

### ISSUE THREAD

**Issue by ilyaigpetrov** [gajananpp/puppeteer-extension-transport#1]
I no longer in need of using puppeteer right now, but I want to leave a comment that may help you with your project.

Manifest V3 specifications on the start prohibited `unsafe-eval` totally. Then the team realized the need for `eval` is widespread so they invented sandboxes feature: https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/.

My offer: maybe you can get rid of unsafe-eval and use sandboxes instead?

**Comment by gajananpp** [comment]
@ilyaigpetrov  Thank you for your suggestion. 

I have added one optional parameter called functionSerializer which can be specified  to provide custom handler for `new Function()`, so if needed user can provide logic to eval in sandbox page.

If this parameter is not specified then it will check if `unsafe_eval` permission is given to extension, if given it will continue to use `new Function()` and if permission not given it is set to empty function, in this case, eval will directly happen on target page. 

This way it not necessary to specify unsafe_eval in manifest.json. Also i have added examples with extension v2 and extension v3 in examples folder. You can check updated docs [here](https://github.com/gajananpp/puppeteer-extension-transport/blob/main/docs/README.md).

**Comment by ilyaigpetrov** [comment]
Thank you!
