### ISSUE TITLE
Closing tabs does not work?

### ISSUE THREAD

**Issue by bestplay9384** [gajananpp/puppeteer-extension-transport#3]
Hey @gajananpp ,

Any idea why in release 0.0.6 `await page.close()` is not working? Debugger is detaching from tab but tab is still there.

**Comment by gajananpp** [comment]
Hi @bestplay9384 ,

Puppeteer's `page.close()` internally calls [`Target.closeTarget`](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-closeTarget) command. It is not allowed by browser when called from extension's debugger api. So internally transport [handles it explicitly](https://github.com/gajananpp/puppeteer-extension-transport/blob/main/lib/index.ts#L217-L222) by just detaching debugger. Alternatively you can close tab using [`chrome.tabs.remove`](https://developer.chrome.com/docs/extensions/reference/tabs/#method-remove) api after `await page.close()`
